name: oda_tables
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  get:
  dropdown_button2: ^1.2.1
  restart_app: ^1.1.0

  fluttertoast: ^8.0.9


  


  path_provider: ^2.0.9
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  datetime_picker_formfield: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true

  # To add assetss to your application, add an assetss section, like this:
  assets:
    - assets/db.db
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets\fonts\Cairo-Regular.ttf
        - asset: assets\fonts\Cairo-Bold.ttf
          weight: 600
        - asset: assets\fonts\Cairo-ExtraBold.ttf
          weight: 700
        - asset: assets\fonts\Cairo-ExtraLight.ttf
          weight: 300
        - asset: assets\fonts\Cairo-Light.ttf
          weight: 400
        - asset: assets\fonts\Cairo-Medium.ttf
          weight: 500
        


